### ISSUE TITLE
Capacitor 6 support

### ISSUE THREAD

**Issue by mley** [bugfender/bugfender-capacitor#12]
Are there any plans to support Capacitor 6 soon? 

Play Store requires target SDK 34 (Android 14) from August 1, which requires Capacitor 6.

**Comment by jgimenez** [comment]
Hi there, we're currently working on it and we expect to have it by the end of this week. Stay tuned!

**Comment by mley** [comment]
That sounds great. Thank you.

**Comment by jgimenez** [comment]
The update is now published in npmjs, version 3.0.0.
